# arguments for dataset
dataset: burn
nclass: 3
crop_size: 513
data_root: ./

# arguments for training
epochs: 80
batch_size: 1 # Reduced for CPU training
lr: 0.0001 # Reduced learning rate for CPU
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255

criterion_u:
  name: CELoss
  kwargs:
    ignore_index: 255

# arguments for model
model:
  backbone:
    type: model.backbone.mit.mit_b5
    kwargs:
      embed_dims: [64, 128, 320, 512]
      pretrained: False
  decoder:
    type: model.semseg.allspark.SemiDecoder
    kwargs:
      num_heads: 2
      num_class: 3
      in_planes: [64, 128, 320, 512]
      image_size: 513
      warmup_epoch: 5
      embedding_dim: 768 